name: Test Next.js v14

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install HarperDB
        run: npm i -g harperdb@4.4.8

      - name: Start HarperDB
        env:
          TC_AGREEMENT: yes
          HDB_ADMIN: hdb_admin
          HDB_ADMIN_PASSWORD: password
          ROOTPATH: /hdb
          OPERATIONSAPI_NETWORK_PORT: 9925
          HTTP_PORT: 9926
          THREADS_COUNT: 1
          LOGGING_STDSTREAMS: true
          LOGGING_LEVEL: debug
          AUTHENTICATION_AUTHORIZELOCAL: false
        run: harperdb start && sleep 5

      - name: Install Next.js v14 Fixture dependencies
        working-directory: fixtures/next-14
        run: |
          npm install
          npx playwright install chromium --with-deps

      - name: Run Next.js v14 Fixture tests
        working-directory: fixtures/next-14
        run: npm run test

      - uses: actions/upload-artifact@v4
        working-directory: fixtures/next-14
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
