name: Next.js Version Matrix Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Skip for now
  if: ${{ false }}
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        next-version: [9, 10, 11, 12, 13, 14, 15]
        node-version: [16, 18, 20, 22]
        # exclude:
        # - next-version: 9
        # node-version: 18

    steps:
      - uses: actions/checkout@v4
      # TODO: invoke the integration container
      # TODO: find interoperability with the scripts/run-integration-tests.js
